version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        HTTPS_PROXY: ${https_proxy}
    container_name: golib
    env_file: .env
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file: postgres.env
    ports: 
      - "5432:5432"
